### ISSUE TITLE
Make it a template

### ISSUE THREAD

**Issue by szepeviktor** [rosswintle/quick-wp-website#1]
> You should fork it and use it as a template for your own thing

[![Template checkbox](https://github.com/rosswintle/quick-wp-website/assets/952007/c5a186ba-cf1a-4dfe-8a99-842232b4571d)](https://github.com/rosswintle/quick-wp-website/settings)

https://github.com/rosswintle/quick-wp-website/settings

Check the checkbox ✔️

**Comment by rosswintle** [comment]
I LOVE that you're so keen to help. Normally it would be incredibly useful.

But I'd like to suggest that you wait until some more commits have been made to repositories before trying to suggest changes?

In this case the template is actually https://github.com/rosswintle/small-site-template and THIS repo is a site that I've created from the template. I've just not got past the cloning bit yet.

I'll make the change over there. Thanks for pointing out that feature.
